[tool.poetry]
name = "discord-bot"
version = "0.1.0"
description = ""
authors = ["YourName"]

[tool.poetry.dependencies]
python = "^3.10"
flask = "^2.0.0"
discord.py = "^2.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"